# Generated by Django 5.2 on 2025-04-17 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prepared_by', models.CharField(max_length=100)),
                ('prepared_date', models.DateField()),
                ('reviewed_by', models.CharField(max_length=200)),
                ('review_date', models.DateField()),
                ('approved_by', models.CharField(max_length=200)),
                ('approved_date', models.DateField()),
                ('procedure_number', models.CharField(max_length=50)),
                ('assembly_number', models.CharField(max_length=50)),
                ('revision_number', models.CharField(max_length=20)),
                ('tools', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('order_date', models.DateField()),
                ('due_date', models.DateField()),
                ('mo_status', models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], max_length=20)),
                ('lot_number', models.CharField(max_length=5)),
                ('codeitem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.codeitem')),
            ],
        ),
        migrations.AddField(
            model_name='codeitem',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.procedure'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(null=True)),
                ('important', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
