# Generated by Django 5.2 on 2025-04-23 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='codeitems/'),
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_id', models.CharField(max_length=50)),
                ('required_quantity', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='components/')),
                ('codeitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='tasks.codeitem')),
            ],
        ),
    ]
