# Generated by Django 5.2 on 2025-04-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_codeitem_image_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeitem',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
