# Generated by Django 5.2 on 2025-04-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_codeitem_image_alter_component_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='pos_x',
            field=models.PositiveIntegerField(default=0, help_text='px desde el borde izquierdo'),
        ),
        migrations.AddField(
            model_name='component',
            name='pos_y',
            field=models.PositiveIntegerField(default=0, help_text='px desde el borde superior'),
        ),
        migrations.AddField(
            model_name='component',
            name='z_index',
            field=models.PositiveIntegerField(default=1, help_text='Orden de apilado'),
        ),
    ]
